version: "2"

services:
  mysqldb:
    image: mysql:5.7

    networks:
      - backendNetwork

    environment:
      MYSQL_DATABASE: employee_management_system
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      - 3306:3306

  delicamart-backend:
    image: openjdk:11
    container_name: delicamart-backend
    volumes:
      - ./delicamart-backend/target/ecommerce-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employee_management_system?autoReconnect=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=root
    networks:
      - backendNetwork
      - frontendNetwork

    depends_on:
      - mysqldb

  angular:
    container_name: angular_container
    build:
      context: ./delicamart-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - delicamart-backend
    networks:
      - frontendNetwork


volumes:
  dockerAngularSpringDatabaseData:

networks:
  backendNetwork:
  frontendNetwork:
