version: "2"

services:
  mysqldb:
    image: mysql:8-oracle

    networks:
      - springmysql-net
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=delicamartdb

  delicamart-backend:
    image: openjdk:11
    container_name: delicamart-backend
    volumes:
      - ./delicamart-backend/target/ecommerce-0.0.1-SNAPSHOT.jar:/application.jar
    command: ["java", "-jar", "application.jar"]
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/delicamartdb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

networks:
  springmysql-net:
